#!/usr/bin/env bash
# Prevent commiting files containing "do not commit"
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
# shellcheck source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/../__common"

PATTERN="DO NOT COMMIT"

if [[ -z "${IGNORE_DO_NOT_COMMIT:-}" ]]; then
    LOGGER=error
else
    LOGGER=warn
fi

# Loop over staged files and check for PATTERN
get_arguments_or_staged_files ".*" "$@"
ERROR=false
for file in "${FILES[@]:-}"; do
    rg -qi "$PATTERN" "$file" &>/dev/null || continue
    "$LOGGER" "$PATTERN found in $file"
    ERROR=true
done

if [[ "$ERROR" != "false" ]]; then
    if [[ -z "${IGNORE_DO_NOT_COMMIT:-}" ]]; then
        exit 1
    fi
fi
