#!/usr/bin/env bash
# Prevent commiting files containing "do not commit"
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

PATTERN="DO NOT COMMIT"
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if [[ -z "${IGNORE_DO_NOT_COMMIT:-}" ]]; then
    COLOR="$RED"
else
    COLOR="$YELLOW"
fi

# Loop over staged files and check for PATTERN
# Filter only added (A), copied (C), modified (M) files
OIFS="$IFS"
IFS=$'\n'
ERROR=false
for file in $(git diff --staged --name-only --diff-filter=ACM); do
    { git show :0:"$file" | grep -Eqi "$PATTERN" &>/dev/null; } || continue
    echo -e >&2 "${COLOR}$SCRIPT_NAME: $PATTERN found in $file${NC}"
    ERROR=true
done
IFS="$OIFS"

if [[ "$ERROR" != "false" ]]; then
    if [[ -z "${IGNORE_DO_NOT_COMMIT:-}" ]]; then
        exit 1
    fi
fi
