#!/usr/bin/env bash
# Run swiftlint on Swift files before commit
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
# shellcheck source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/../__common"

if [[ -n "${IGNORE_SWIFT_LINT:-}" ]]; then
    warn "IGNORE_SWIFT_LINT enabled; skipping checks"
    exit 0
fi

if ! command -v "swiftlint" &>/dev/null ; then
    warn "swiftlint not found; skipping checks"
    exit 0
fi

REPO_DIR="$(repo_dir)"
if [[ ! -f "$REPO_DIR/.swiftlint.yml" ]]; then
    trace "no config file found; skipping checks"
    exit 0
fi

get_arguments_or_staged_files '\.swift$' "$@"
if [[ ${#FILES[@]} -ne 0 ]]; then
    if [[ $VERBOSE -lt 1 ]]; then
        ARGS=("--quiet")
    else
        ARGS=()
    fi
    exec swiftlint lint "${ARGS[@]}" "${FILES[@]}"
fi
