#!/usr/bin/env bash
# Run "scripts/lint" in the project repository if it exists
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
REPO_DIR="$(git rev-parse --show-toplevel)"
cd "$REPO_DIR"

YELLOW='\033[1;33m'
GRAY='\033[90m'
CYAN='\033[36m'
NC='\033[0m' # No Color

# Set VERBOSE=non-number to VERBOSE=1, otherwise use the number
[[ "${VERBOSE:-0}" =~ ^[0-9]+$ ]] && VERBOSE="${VERBOSE:-0}" || VERBOSE=1
trace () {
    [[ "$VERBOSE" -lt 2 ]] || echo >&2 -e "🔬 ${GRAY}$*${NC}"
}
debug () {
    [[ "$VERBOSE" -lt 1 ]] || echo >&2 -e "🔍 ${CYAN}$SCRIPT_NAME: $*${NC}"
}
warn () {
    echo >&2 -e "⚠️ ${YELLOW}$SCRIPT_NAME: $*${NC}"
}

if [[ ! -f ".swiftlint.yml" ]]; then
    trace "no config file found; skipping checks"
    exit 0
fi

if ! command -v "swiftlint" &>/dev/null ; then
    warn "swiftlint not found; skipping checks"
    exit 0
fi

if [[ -n "${IGNORE_SWIFT_LINT:-}" ]]; then
    warn "IGNORE_SWIFT_LINT enabled; skipping checks"
    exit 0
fi

# Filter only added (A), copied (C), modified (M) files
OIFS="$IFS"
IFS=$'\n'
STAGED_FILES=()
for file in $(git diff --staged --name-only --diff-filter=ACM); do
    if [[ "$file" =~ \.swift$ ]]; then
        STAGED_FILES+=("$file")
    fi
done
IFS="$OIFS"

if [[ ${#STAGED_FILES[@]} -ne 0 ]]; then
    if [[ $VERBOSE -lt 1 ]]; then
        ARGS=("--quiet")
    else
        ARGS=()
    fi
    exec swiftlint lint "${ARGS[@]}" "${STAGED_FILES[@]}"
fi
