#!/usr/bin/env bash
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
REPO_DIR="$(git rev-parse --show-toplevel)"
cd "$REPO_DIR"

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if ! command -v "scripts/lint" &>/dev/null ; then
    echo -e >&2 "${YELLOW}$SCRIPT_NAME: scripts/lint not found; skipping lint${NC}"
    exit 0
fi

# Filter only added (A), copied (C), modified (M) files
OIFS="$IFS"
IFS=$'\n'
declare -a STAGED_FILES
for file in $(git diff --staged --name-only --diff-filter=ACM); do
    STAGED_FILES+=("$file")
done
IFS="$OIFS"

exec "scripts/lint" "${STAGED_FILES[@]}"
