#!/usr/bin/env bash
# Run ripsecrets to avoid commiting secrets to repository
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
# shellcheck source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/../__common"

if [[ -n "${IGNORE_SECRETS:-}" ]]; then
    warn "IGNORE_SECRETS enabled; skipping checks"
    exit 0
fi

if ! command -v "ripsecrets" &>/dev/null ; then
    warn "ripsecrets not installed; skipping checks"
    exit 0
fi

get_arguments_or_staged_files ".*" "$@"
if (( ${#FILES[@]} > 0 )); then
    exec ripsecrets --strict-ignore "${FILES[@]}"
fi
