#!/usr/bin/env bash
# Run ripsecrets to avoid commiting secrets to repository
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
REPO_DIR="$(git rev-parse --show-toplevel)"
cd "$REPO_DIR"

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if [[ -n "${IGNORE_SECRETS:-}" ]]; then
    echo -e >&2 "${YELLOW}$SCRIPT_NAME: IGNORE_SECRETS enabled; skipping checks${NC}"
    exit 0
fi

if ! command -v "ripsecrets" &>/dev/null ; then
    echo -e >&2 "${YELLOW}$SCRIPT_NAME: ripsecrets not installed; skipping checks${NC}"
    exit 0
fi

# Filter only added (A), copied (C), modified (M) files
OIFS="$IFS"
IFS=$'\n'
STAGED_FILES=()
for file in $(git diff --staged --name-only --diff-filter=ACM); do
    STAGED_FILES+=("$file")
done
IFS="$OIFS"

if [[ ${#STAGED_FILES[@]} -ne 0 ]]; then
    exec ripsecrets --strict-ignore "${STAGED_FILES[@]}"
fi
